<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Please check "{modelName}" into "{moduleName}" config' => 'Пожалуйста, проверте настройку "{modelName}" модуля "{moduleName}"',
    'The POST "source" and "target" params has missed.' => 'Требуются POST параметры "source" и "target"',
    'Save failure {reason}' => 'Сохраниение не удалось по причине {reason}',
    'The POST param(s) of item pk has missed.' => 'Требуется первичный ключ элемента в POST параметрах',
    'Wrong POST data' => 'Некорректные POST данные',
    'The requested item does not exist.' => 'Запрошеный элемент не найден',
];
