<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Double-click on node for open in form for update or delete<br>To delete relation double-click on the connection.<br>To connect move node (parent) to other node (child).' => 'Двойной щелчёк на узел для открытия в форме редактирования/удаления.<br>Двойной щелчёк на соеденительную линию для удаления отношения<br>Для привязки перетащите узел (предок) на другой узел (потомок)',
    'Connection item to other item' => 'Отношение элемента к другому элементу',
    'Dotted line mean connection child to his parent' => 'Пунктирная линия соединяет дочерний элемент с родительским',
    'Info' => 'Инфо',
    'Search for...' => 'Искать...',
    'click on element' => 'клик на элементе',
];
